	['macfarranch'] = {
    label = 'Macfarlane Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
['emeraldranch'] = {
    label = 'Emerald Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
['pronghornranch'] = {
    label = 'Pronghorn Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
['downesranch'] = {
    label = 'Downes Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
['hillhavenranch'] = {
    label = 'Hill Haven Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
    ['hangingdogranch'] = {
    label = 'Hanging Dog Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
['bayounwaranch'] = {
    label = 'Bayou Nwa Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
['gaptoothranch'] = {
    label = 'Gaptooth Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
['adlerranch'] = {
    label = 'Adler Rancher',
    type = 'rancher',
    defaultDuty = true,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Trainee Rancher', payment = 3 },
        ['1'] = { name = 'Ranch Hand', payment = 5 },
        ['2'] = { name = 'Senior Rancher', payment = 7 },
        ['3'] = { name = 'Ranch Manager', isboss = true, payment = 10 },
        ['4'] = { name = 'Ranch Boss', isboss = true, payment = 15 },
    },
},
